### ISSUE TITLE
sql files won't unlink

### ISSUE THREAD

**Issue by Juanitaag1** [MeyAyre/SpicyShrimpBIT286#8]
Could not do pull 
tried to do a pull
should be able to make a pull
instead got message that files can not unlink

**Comment by Juanitaag1** [comment]
The issue was resolved and now able to make a pull

**Comment by MikeTheGreat** [comment]
I'm glad that you went through and did all this - filed an issue, fixed something, then marked it fixed.
That said, this sounds like a problem using Git/GitHub, as opposed to a defect in the software itself.  I'm not gonna ding you for this, but be aware that if you're interviewing for a job (say) and they ask you if you've ever fixed a bug using a bug tracking system (Ex: by using GitHub issues) they're going to expect that you actually changed the software product (instead of fixing a problem with Git)
